---
abstract: 'Module::Build meets plugins'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.0, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Pluggable
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Module::Build::Pluggable:
    file: lib/Module/Build/Pluggable.pm
    version: 0.10
  Module::Build::Pluggable::Base:
    file: lib/Module/Build/Pluggable/Base.pm
    version: 0
  Module::Build::Pluggable::GithubMeta:
    file: lib/Module/Build/Pluggable/GithubMeta.pm
    version: 0
  Module::Build::Pluggable::Repository:
    file: lib/Module/Build/Pluggable/Repository.pm
    version: 0.10
  Module::Build::Pluggable::Util:
    file: lib/Module/Build/Pluggable/Util.pm
    version: 0
  Test::Module::Build::Pluggable:
    file: lib/Test/Module/Build/Pluggable.pm
    version: 0
requires:
  Class::Accessor::Lite: 0
  Class::Method::Modifiers: 0
  Data::OptList: 0
  File::Basename: 0
  File::Path: 0
  File::Temp: 0
  Module::Build: 0.38
  Module::Load: 0
  Test::SharedFork: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/Module-Build-Pluggable/issues
  homepage: https://github.com/tokuhirom/Module-Build-Pluggable
  repository: git://github.com/tokuhirom/Module-Build-Pluggable.git
version: 0.10
x_contributors:
  - 'tokuhirom <tokuhirom@gmail.com>'
